---

- name: Install python-apt via command module
  command: apt-get install python-apt -y

- name: Install apache on instances
  apt: name=apache2 update_cache=yes state=present

- name: copy my index html
  copy: src=index.html dest=/var/www/html/index.html

- name: Keep the service started
  service:
    name: apache2
    state: started
    
